---
apiVersion: v1
kind: Namespace
metadata:
  name: unifi 
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: unifi-controller-pv
  namespace: unifi 
spec:
  capacity:
    storage: 64Gi
  accessModes:
    - ReadWriteMany
  iscsi:
     targetPortal: CHANGEME:3260
     portals: ['CHANGEME:3260']
     iqn: CHANGEME
     lun: CHANGEME
     fsType: 'ext4'
     readOnly: false
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: unifi-controller-claim
  namespace: unifi 
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 64Gi
  volumeName: "unifi-controller-pv"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unifi-controller 
  namespace: unifi 
  labels:
    app: unifi-controller 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unifi-controller 
  template:
    metadata:
      labels:
        app: unifi-controller 
        name: unifi-controller 
    spec:
      containers:
      - name: unifi-controller 
        image: linuxserver/unifi-controller
        imagePullPolicy: Always
        volumeMounts:
        - name: unifi-controller-persistent-storage
          mountPath: /config
      volumes:
      - name: unifi-controller-persistent-storage
        persistentVolumeClaim:
          claimName: unifi-controller-claim 
---
apiVersion: v1
kind: Service
metadata:
  name: unifi-controller-service
  namespace: unifi 
spec:
  type: LoadBalancer
  selector:
    app: unifi-controller 
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    name: http
  - protocol: TCP
    port: 8443
    targetPort: 8443
    name: https
  - protocol: TCP
    port: 8081
    name: unifi-comm-port-1
    targetPort: 8081
  - protocol: TCP
    port: 8843
    targetPort: 8843
    name: unifi-comm-port-2
  - protocol: TCP
    port: 8880
    targetPort: 8880
    name: unifi-comm-port-3
  - protocol: TCP
    port: 6789
    targetPort: 6789
    name: unifi-comm-port-4
